### ISSUE TITLE
Acompanhamento projetos Ação Jovem da Rede CUCA

### ISSUE THREAD

**Issue by Andreqlp** [Mutirao/painel-de-controle#66]
Repositório: https://github.com/Mutirao/6acaojovem
Pasta no Drive: https://drive.google.com/drive/u/0/folders/0B4Q7Y_cuhmVKUWxBa1JyMEE2YnM

A proposta é apresentar ferramentas de trabalho colaborativo e criar um ambiente de transparência para as ações dos projetos, semelhante ao http://culturadigital.br/2acaojovemjangurussu/

Esse ano serão aprovados 15 projetos nos Cucas Jangurussu, Mondubim e Barra. A equipe de suporte será formada por facilitadores, assessoria de imprensa e transparência (é nois).

Cronograma das atividades:
8/6 - lançamento e início das inscrições
14/6 - resultado
23/6 - assinatura do contrato
30/6 - liberação do recurso e realização dos projetos
30/7 - culminância

**Comment by uira** [comment]
- [ ] Marcar reunião e colocar na agenda
